export const VIDEO_INIT = 'VIDEO_INIT';
export const VIDEO_LOAD_START = 'VIDEO_LOAD_START';
export const VIDEO_PROGRESS = 'VIDEO_PROGRESS';
export const VIDEO_SUSPEND = 'VIDEO_SUSPEND';
export const VIDEO_ABORT = 'VIDEO_ABORT';
export const VIDEO_ERROR = 'VIDEO_ERROR';
export const VIDEO_EMPTIED = 'VIDEO_EMPTIED';
export const VIDEO_STALLED = 'VIDEO_STALLED';
export const VIDEO_LOADED_METADATA = 'VIDEO_LOADED_METADATA';
export const VIDEO_LOADED_DATA = 'VIDEO_LOADED_DATA';
export const VIDEO_CAN_PLAY = 'VIDEO_CAN_PLAY';
export const VIDEO_CAN_PLAY_THROUGH = 'VIDEO_CAN_PLAY_THROUGH';
export const VIDEO_PLAYING = 'VIDEO_PLAYING';
export const VIDEO_WAITING = 'VIDEO_WAITING';
export const VIDEO_SEEKING = 'VIDEO_SEEKING';
export const VIDEO_SEEKED = 'VIDEO_SEEKED';
export const VIDEO_ENDED = 'VIDEO_ENDED';
export const VIDEO_DURATION_CHANGE = 'VIDEO_DURATION_CHANGE';
export const VIDEO_TIME_UPDATE = 'VIDEO_TIME_UPDATE';
export const VIDEO_PLAY = 'VIDEO_PLAY';
export const VIDEO_PAUSE = 'VIDEO_PAUSE';
export const VIDEO_RATE_CHANGE = 'VIDEO_RATE_CHANGE';
export const VIDEO_RESIZE = 'VIDEO_RESIZE';
export const VIDEO_VOLUME_CHANGE = 'VIDEO_VOLUME_CHANGE';
export const VIDEO_TOGGLE_LOOP = 'VIDEO_TOGGLE_LOOP';

export const error = ['VIDEO_ERROR', 'VIDEO_ABORT'];
export const networkState = [
  'VIDEO_INIT',
  'VIDEO_LOAD_START',
  'VIDEO_PROGRESS',
  'VIDEO_SUSPEND',
  'VIDEO_ABORT',
  'VIDEO_ERROR',
  'VIDEO_EMPTIED',
  'VIDEO_STALLED',
];

export const readyState = [
  'VIDEO_INIT',
  'VIDEO_LOADED_METADATA',
  'VIDEO_LOADED_DATA',
  'VIDEO_CAN_PLAY',
  'VIDEO_CAN_PLAY_THROUGH',
  'VIDEO_WAITING',
  'VIDEO_RESIZE',
];

export const time = [
  'VIDEO_SEEKING',
  'VIDEO_SEEKED',
  'VIDEO_ENDED',
  'VIDEO_TIME_UPDATE',
];
