export const FILTER_DESTROY = 'FILTER_DESTROY';
export const FILTER_MOVE = 'FILTER_MOVE';
export const FILTER_RESIZE = 'FILTER_RESIZE';
export const FILTER_TOGGLE_LOCKED = 'FILTER_TOGGLE_LOCKED';
export const FILTER_TOGGLE_VISIBILITY = 'FILTER_TOGGLE_VISIBILITY';

